###
POST {{host}}/api/menus
Content-Type: application/json

{
  "name": "event",
  "price": 200,
  "menuGroupId": "f1860abc-2ea1-411b-bd4a-baa44f0d5580",
  "displayed": true,
  "menuProducts": [
    {
      "productId": "c5ee925c-3dbb-4941-b825-021446f24446",
      "quantity": 1
    }
  ]
}

###
PUT {{host}}/api/menus/0b8d208e-ca3a-4df5-afc9-acc35ec9323e/price
Content-Type: application/json

{
  "price": 2000
}

###
PUT {{host}}/api/menus/0b8d208e-ca3a-4df5-afc9-acc35ec9323e/display

###
PUT {{host}}/api/menus/0b8d208e-ca3a-4df5-afc9-acc35ec9323e/hide

###
GET {{host}}/api/menus
