###
POST {{host}}/api/menus
Content-Type: application/json

{
  "name": "wwwwwwwww",
  "price": 1111,
  "menuGroupId": "f1860abc-2ea1-411b-bd4a-baa44f0d5580",
  "displayed": true,
  "menuProducts": [
    {
      "productId": "be4a53ad-7033-42e3-9e40-cd7d57643bfa",
      "quantity": 11
    },
    {
      "productId": "eac2cf52-23a2-4b05-a741-dfdf15d69666",
      "quantity": 12
    },
    {
      "productId": "c5ee925c-3dbb-4941-b825-021446f24446",
      "quantity": 13
    }
  ]
}

###
PUT {{host}}/api/menus/0b8d208e-ca3a-4df5-afc9-acc35ec9323e/price
Content-Type: application/json

{
  "price": 100
}

###
PUT {{host}}/api/menus/0b8d208e-ca3a-4df5-afc9-acc35ec9323e/display

###
PUT {{host}}/api/menus/0b8d208e-ca3a-4df5-afc9-acc35ec9323e/hide

###
GET {{host}}/api/menus
