###
POST {{host}}/api/menus
Content-Type: application/json

{
  "name": "후라이드2222",
  "price": 13000,
  "menuGroupId": "f1860abc-2ea1-411b-bd4a-baa44f0d5580",
  "displayed": true,
  "menuProducts": [
    {
      "productId": "3b528244-34f7-406b-bb7e-690912f66b10",
      "quantity": 2
    }
  ]
}

###
PUT {{host}}/api/menus/0b8d208e-ca3a-4df5-afc9-acc35ec9323e/price
Content-Type: application/json

{
  "price": 100
}

###
PUT {{host}}/api/menus/0b8d208e-ca3a-4df5-afc9-acc35ec9323e/display

###
PUT {{host}}/api/menus/0b8d208e-ca3a-4df5-afc9-acc35ec9323e/hide

###
GET {{host}}/api/menus
