###
POST {{host}}/tobe/api/orders
Content-Type: application/json

{
  "type": "EAT_IN",
  "orderTableId": "4d90c806-76f0-48d5-be9b-9b85b05df0f3",
  "orderLineItems": [
    {
      "menuId": "a64af6ca-c34d-4cd8-82fe-454abf512d1f",
      "price": 17000,
      "quantity": 2
    }
  ]
}

###
PUT {{host}}/tobe/api/orders/b8a8947d-9591-4a0c-ab9f-e74eb7f14d82/accept

###
PUT {{host}}/tobe/api/orders/b8a8947d-9591-4a0c-ab9f-e74eb7f14d82/serve

###
PUT {{host}}/tobe/api/orders/69d78f38-3bff-457c-bb72-26319c985fd8/start-delivery

###
PUT {{host}}/tobe/api/orders/69d78f38-3bff-457c-bb72-26319c985fd8/complete-delivery

###
PUT {{host}}/tobe/api/orders/b8a8947d-9591-4a0c-ab9f-e74eb7f14d82/complete

###
GET {{host}}/tobe/api/orders
