###
POST {{host}}/api/products
Content-Type: application/json

{
  "name": "하이",
  "price": 17000
}

###
PUT {{host}}/api/products/c5ee925c-3dbb-4941-b825-021446f24446/price
Content-Type: application/json

{
  "price": 700
}

###
GET {{host}}/api/products
