###
POST {{host}}/api/products
Content-Type: application/json

{
  "name": "강정치킨",
  "price": 17000
}

> {%
    client.global.set("productId", response.body["id"])
%}

###
PUT {{host}}/api/products/{{productId}}/price
Content-Type: application/json

{
  "price": 18000
}

###
GET {{host}}/api/products
